# Generated by Django 2.2 on 2019-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('producticon', models.ImageField(default='images/defaultimage.jpg', height_field='image_height', upload_to='images/', width_field='image_width')),
                ('stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(verbose_name=100)),
                ('image_width', models.PositiveIntegerField(verbose_name=100)),
                ('category', models.CharField(choices=[('SKINCARE', 'Skincare'), ('CLEANSING', 'Cleansing'), ('MAKEUP', 'Makeup'), ('VITAMIN', 'Vitamin')], default='SKINCARE', max_length=10)),
            ],
        ),
    ]
